#!/usr/bin/env zsh

# Build and deploy to mini.

mv _config.yml _config_dev.yml
mv _config_deploy.yml _config.yml

./tasks/jekyll && \
  rsync -az --delete --exclude '.git' _site/ ~/Repositories/metaskills.github.com && \
  cd ~/Repositories/metaskills.github.com && \
  git add . && \
  gca -m "Automatic deploy commit." && \
  grbmc

mv _config.yml _config_deploy.yml
mv _config_dev.yml _config.yml

